const state={data:null,tab:'diagnose'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=o=>Object.values(o||{}).join(' ').toLowerCase();
function recordCard(r){const fields=[['Likely causes / checks',r['Likely causes to investigate']||r['Likely causes']],['Diagnostic checks',r['Diagnostic questions / checks']||r['Diagnostic checks']],['Corrective actions',r['Conditional corrective actions']||r['Corrective actions']],['Verification',r['Verification / acceptance']||r['Verification']],['Safety / restrictions',r['Safety / restrictions']]];return `<article class="record"><div class="record-top"><div><h3>${esc(r['Problem / Symptom']||r['Colour issue']||r['Scenario']||r['Rule ID']||r['Profile ID']||'Record')}</h3><p>${esc(r.ID||r['Rule ID']||r['Profile ID']||'')} · ${esc(r.Module||r['Visible symptom']||r.Material||'')}</p></div><span class="pill">${esc(r.Status||r.Severity||'Reference')}</span></div>${fields.filter(x=>x[1]).map(x=>`<details><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p></details>`).join('')}</article>`}
function populate(){const d=state.data;const mods=[...new Set(d.Troubleshooting.map(x=>x.Module).filter(Boolean))].sort();['#diagModule','#kbModule'].forEach(sel=>$(sel).innerHTML='<option value="">All modules</option>'+mods.map(x=>`<option>${esc(x)}</option>`).join(''));$('#recordCount').textContent=d.Troubleshooting.length+d.Colour_Variation.length;$('#version').textContent='v0.1 · local knowledge base';renderDiag();renderKB();renderColour();renderCure();}
function renderDiag(){const q=$('#diagSearch').value.trim().toLowerCase(),m=$('#diagModule').value,s=$('#diagSubstrate').value,t=$('#diagThickness').value;let rows=state.data.Troubleshooting.filter(r=>(!q||text(r).includes(q))&&(!m||r.Module===m));if(s||t){rows=rows.filter(r=>{const z=text(r);return (!s||z.includes(s.toLowerCase())||['cure','substrate','thickness','appearance','coverage'].some(k=>z.includes(k)))&&(!t||z.includes(t.toLowerCase())||z.includes('thickness')||z.includes('cure'));});}rows=rows.slice(0,30);$('#resultCount').textContent=`${rows.length} matches`;$('#diagResults').innerHTML=rows.length?rows.map(recordCard).join(''):'<div class="muted">No exact matches. Try a broader symptom, or review the Knowledge base tab.</div>';}
function renderKB(){const q=$('#kbSearch').value.trim().toLowerCase(),m=$('#kbModule').value;const rows=state.data.Troubleshooting.filter(r=>(!q||text(r).includes(q))&&(!m||r.Module===m));$('#kbResults').innerHTML=rows.map(recordCard).join('')||'<div class="muted">No records found.</div>';}
function renderColour(){const q=$('#colourSearch').value.trim().toLowerCase();const rows=state.data.Colour_Variation.filter(r=>!q||text(r).includes(q));$('#colourResults').innerHTML=rows.map(recordCard).join('')||'<div class="muted">No colour records found.</div>';}
function renderCure(){const profiles=state.data.Cure_Profiles.filter(r=>r['Profile ID']);$('#cureCards').innerHTML=profiles.map(r=>`<div class="profile"><b>${esc(r.Material)} · ${esc(r['Thickness / section'])}</b><span class="muted">τ: ${esc(r['Illustrative time constant τ (min)'])} min</span><p class="muted">Time to 180°C: ${esc(r['Time to 180°C approx. (min)'])} min</p><p class="muted">Illustrative dwell: ${esc(r['Illustrative cure dwell after 180°C (min)'])} min</p></div>`).join('');$('#cureMatrix').innerHTML='<h3>Thermal diagnostic matrix</h3>'+state.data.Cure_Diagnostic_Matrix.map(recordCard).join('');drawChart(profiles);}
function drawChart(profiles){const svg=$('#cureChart'),W=900,H=430,p={l:65,r:25,t:25,b:55},iw=W-p.l-p.r,ih=H-p.t-p.b;const xMax=30,yMin=25,yMax=205;let out=`<rect width="${W}" height="${H}" fill="#fbfdff"/>`;for(let y=25;y<=200;y+=25){const yy=p.t+ih-(y-yMin)/(yMax-yMin)*ih;out+=`<line x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}" stroke="#d9e2ec"/><text x="${p.l-10}" y="${yy+4}" text-anchor="end" font-size="11" fill="#627d98">${y}°</text>`}for(let x=0;x<=30;x+=5){const xx=p.l+x/xMax*iw;out+=`<line x1="${xx}" x2="${xx}" y1="${p.t}" y2="${H-p.b}" stroke="#edf2f7"/><text x="${xx}" y="${H-p.b+22}" text-anchor="middle" font-size="11" fill="#627d98">${x}</text>`}out+=`<text x="${W/2}" y="${H-10}" text-anchor="middle" font-size="12" fill="#627d98">Minutes</text><text x="18" y="${H/2}" transform="rotate(-90 18 ${H/2})" text-anchor="middle" font-size="12" fill="#627d98">Illustrative part temperature</text>`;const palette=['#1f7a8c','#6b4eff','#d97706','#b42318','#2f855a','#805ad5'];profiles.forEach((r,i)=>{const tau=Number(r['Illustrative time constant τ (min)'])||4;let d='';for(let x=0;x<=30;x+=.5){const temp=25+(200-25)*(1-Math.exp(-x/tau));const xx=p.l+x/xMax*iw,yy=p.t+ih-(temp-yMin)/(yMax-yMin)*ih;d+=(x===0?'M':'L')+xx.toFixed(1)+','+yy.toFixed(1)+' ';}out+=`<path d="${d}" fill="none" stroke="${palette[i%palette.length]}" stroke-width="2.5"/><text x="${p.l+iw-5}" y="${p.t+18+i*17}" text-anchor="end" font-size="11" fill="${palette[i%palette.length]}">${esc(r.Material+' '+r['Thickness / section'])}</text>`});svg.innerHTML=out;}
function switchTab(tab){state.tab=tab;$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+tab));}
async function boot(){state.data=await fetch('data.json').then(r=>r.json());populate();$$('.tabs button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));['#diagSearch','#diagModule','#diagSubstrate','#diagThickness'].forEach(s=>$(s).addEventListener('input',renderDiag));['#kbSearch','#kbModule'].forEach(s=>$(s).addEventListener('input',renderKB));$('#colourSearch').addEventListener('input',renderColour);$('#resetDiag').addEventListener('click',()=>{$('#diagSearch').value='';$('#diagModule').value='';$('#diagSubstrate').value='';$('#diagThickness').value='';$('#diagUrgency').value='Routine';renderDiag()});$('#safetyBtn').addEventListener('click',()=>$('#safetyModal').classList.remove('hidden'));$('#closeSafety').addEventListener('click',()=>$('#safetyModal').classList.add('hidden'));$('#ackSafety').addEventListener('click',()=>$('#safetyModal').classList.add('hidden'));if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
boot();
